# Site settings
title: Circumnavigating Cyprus
email: asanton@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Exactly what the title says.
baseurl: ""
url: "http://circumnavigatingcyprus.github.io" # the base hostname & protocol for your site
umich_link: "https://www.lsa.umich.edu/ummaa/people/ci.antoniouanna_ci.detail"

# Map
map-tileset: 'https://api.tiles.mapbox.com/v4/opleban.mdj03cbc/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoib3BsZWJhbiIsImEiOiI0VXNzcXFRIn0.uE_om5U3KbYO_Xy-tsSRiQ'

# Build settings
markdown: kramdown
permalink: pretty
post_categories:
- interviews
- participant photography
- team member updates
- trekking
prose:
  ignore:
  - _config.yml
  - /_layouts
  - /_includes
  - /_sass
  - /css
  - /js
  - /en
  - /tr
  - /gr
  - /_site
  - /_plugins
  - index.html
  - .gitignore
  - .ruby-version
  - /.sass-cache
  - feed.xml
  - index.md
  - Gemfile
  - Gemfile.lock
  siteurl: "http://circumnavigatingcyprus.github.io"
  media: "media"
  metadata:
    _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name: "identifier"
      field:
        element: "text"
        label: "Enter a Post Identifier. This should be same for translations of the post."
    - name: language
      field:
        element: "select"
        label: "Choose the correct language"
        options:
        - name: English
          value: "en"
        - name: Greek
          value: "gr"
        - name: Turkish
          value: "tr"
    - name: "title"
      field:
        element: "text"
        label: "title"
    - name: "lat"
      field:
        element: "text"
        label: "Latitude"
        placholder: "Enter Latitude Coordinates"
    - name: "lng"
      field:
        element: "text"
        label: "Longitude"
        placholder: "Enter Longitude Coordinates"
    - name: "image"
      field:
        element: "text"
        label: "Preview Image"
        placeholder: "Enter the a link to your preview image"
    - name: "categories"
      field:
        element: "multiselect"
        label: "Add Categories"
        alterable: true
        options:
        - name: "English"
          value: "en"
        - name: "Greek"
          value: "gr"
        - name: "Turkish"
          value: "tr"
        - name: "Trekking"
          value: "trekking"
        - name: "Interviews"
          value: "interviews"
        - name: "Participant Photography"
          value: "participant photography"
        - name: "Team Member Updates"
          value: "team member updates"
    - name: "tags"
      field:
        element: "multiselect"
        alterable: true
        label: "Add Tags"
    - name: "author"
      field:
        element: "text"
        label: "author, Πώς σε λένε?"
        value: "Anna Antoniou"
    - name: "map"
      field:
        element: "checkbox"
        label: "Appears on Map?"
    - name: "popupContent"
      field:
        element: "checkbox"
        label: "Map popup?"
    - name: "teaser"
      field:
        element: "textarea"
        label: "Post Teaser"
        help: "The text you'd like to appear for the popup content on the map"
        placeholder: "popup teaser text"