# Site settings
title: Anna's Site
github: [Repository metadata]
email: asanton@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Anna's Travelogue -mapified!
baseurl: "/anna-site"
url: "http://opleban.github.io/anna-site" # the base hostname & protocol for your site
umich_link: "https://www.lsa.umich.edu/ummaa/people/ci.antoniouanna_ci.detail"

# Map
map-tileset: 'https://api.tiles.mapbox.com/v4/opleban.mdj03cbc/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoib3BsZWJhbiIsImEiOiI0VXNzcXFRIn0.uE_om5U3KbYO_Xy-tsSRiQ'

# Build settings
markdown: kramdown

gems: 

